/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/ts-logo.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={false}
        far={2}
        near={0}
        fov={34.52}
        position={[0.5, 0.3, 0.5]}
        rotation={[-0.36, 0.75, 0.25]}
      />
      <mesh
        geometry={nodes.Text.geometry}
        material={materials['Matte 2']}
        position={[-0.07, 0.02, 0.09]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 0.94]}
      />
      <mesh geometry={nodes.Rounded_Cube_Flat.geometry} material={materials.Matte} />
    </group>
  )
}

useGLTF.preload('/ts-logo.gltf')
